project:
  type: website

website:
  title: "Matt Carswell"

  search:
    location: navbar
    type: overlay

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mattycars
      - icon: linkedin
        href: https://www.linkedin.com/in/matthew-carswell-7977b3206/

format:
  html:
    theme: quartz
    css: styles.css
    mainfont: Consolas


